name: Build OnePlus-Sm8150-Kernel-OOS11

on:
  push:
    tags:
      - '*'  # This allows any tag push to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "2G"
      CCACHE_HARDLINK: "true"
    steps:
      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "<span class="math-inline">AGENT\_TOOLSDIRECTORY"
\- name\: Install dependencies
run\: \|
sudo apt\-get update \-y 
sudo apt install gcc\-aarch64\-linux\-gnu \-y
sudo apt install gcc\-arm\-linux\-gnueabi \-y
sudo apt install clang\-14 \-y
sudo apt install binutils make python3 libssl\-dev build\-essential bc bison flex unzip libssl\-dev ca\-certificates xz\-utils mkbootimg cpio device\-tree\-compiler git git\-lfs \-y
git clone https\://github\.com/LineageOS/android\_prebuilts\_gcc\_linux\-x86\_aarch64\_aarch64\-linux\-android\-4\.9 aarch64 \-\-depth\=1
git clone https\://github\.com/grm34/proton\-clang \-b ZenMaxBuilder clang \-\-depth\=1
git clone https\://github\.com/khalidaboelmagd/AnyKernel3 \-b oneplus7 \-\-depth\=1
rm \-rf AnyKernel3/\.git
\- name\: Checkout Android 11 kernel source
run\: \|
rm \-rf kernel
git clone \-\-recurse\-submodules https\://github\.com/snowwolf725/android\_kernel\_oneplus\_sm8150 \-b oneplus/OOS\_SM8150\_11\.0 \-\-depth\=1 kernel
cd kernel/KernelSU
git pull
cd \.\./\.\./
\- name\: Setup OOS 11
run\: \|
export KERNEL\_DEFCONFIG\="blu\_spark\_defconfig"
export KERNEL\_CMDLINE\="ARCH\=arm64 CLANG\_TRIPLE\=aarch64\-linux\-gnu\- CROSS\_COMPILE\=aarch64\-linux\-androidkernel\- CROSS\_COMPILE\_ARM32\=arm\-linux\-gnueabi\- LLVM\=1 LLVM\_IAS\=1 O\=out"
export PATH\=</span>(pwd)/clang/bin/:$(pwd)/aarch64/bin/:$PATH
          export ARCH=arm64
          export SUBARCH=arm64
          export LD=ld.lld
          export BRAND_SHOW_FLAG=oneplus
          export TARGET_PRODUCT=msmnile
          cd kernel
          make $KERNEL_CMDLINE CC="ccache clang-14" $KERNEL_DEFCONFIG
          make <span class="math-inline">KERNEL\_CMDLINE CC\="ccache clang\-14" \-j</span>(nproc --all)
          cp out/arch/arm64/boot/Image ../AnyKernel3
          cd ..
      - name: Create AK3 zip for android 11
        run: |
          zip OP7-OOS11-kernel-SU-<span class="math-inline">\{\{ github\.sha \}\}\.zip AnyKernel3/\*
\- name\: Upload to Release \(on tag push only\)
uses\: softprops/action\-gh\-release@v1
if\: github\.ref\_type \=\= 'tag'
with\:
files\: \|
OP7\-OOS11\-kernel\-SU\-</span>{{ github.sha }}.zip
          name: OnePlus7_kernelsu-${{ github.sha }}
          body: |
            Device: Oneplus 7/Oneplus 7Pro/Oneplus 7T/Oneplus 7TPro
            Target: OOS11
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN
